name: Build on microCMS Webhook

on:
  repository_dispatch:
    types: [microcms-content-updated]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate HTML from microCMS
        env:
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
        run: npm run build
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.html
          git diff --staged --quiet || git commit -m "chore: update content from microCMS [skip ci]"
          git remote set-url origin "https://$GH_TOKEN@github.com/biangesite/biange-site-lp.git"
          git push
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}